### ISSUE TITLE
Is hot module reload supported?

### ISSUE THREAD

**Issue by jaybo** [mhingston/QuasarAspNetCoreTemplate#1]
Thanks so much for publishing this.  It's the first working non-typescript example I've found after struggling for days to unite asp.net core 3.1 with quasar.  !!!

It seems to do everything I need, but I'm not finding that the browser auto-refreshes after saving source file changes.  Is it supposed to?

**Comment by mhingston** [comment]
Hi @jaybo, I've made some changes that should fix the hot reloading now.

![1kUYFGpMOB](https://user-images.githubusercontent.com/9764437/79636770-04806680-8172-11ea-82ee-86a532c09b29.gif)

**Comment by jaybo** [comment]
Great!  I tested the update in both VS2019 and VSCode and it worked fine.
